import '@/assets/styles/globals.scss'
import '@/assets/styles/fontawesome.min.css'
import 'swiper/css'
import Script from 'next/script'

export const metadata = {
  title: 'Proyecto 0',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
      <Script src="https://kit.fontawesome.com/da618b3aee.js" crossOrigin="anonymous"></Script>
    </html>
  )
}
